feat: create authorization mechanism
atls-academy/jumpeebunee.github.io pull request #4
Opened 2023-05-17 07:30 UTC by jumpeebunee

2023-05-17 16:52 UTC, TorinAsakura requested changes
Вместо прямого использования console.log() для вывода сообщений об ошибках, ты можешь использовать выбрасывания исключений и обработки их на более высоком уровне. Так будет легче адаптировать код для разных сред выполнения и упростит тестирование.

2023-05-17 16:52 UTC, TorinAsakura commented on auth/scripts/index.ts
> +        const isFindedUsername = credentials.find(user => user.username === username);
полагаю, тут лучшим решением будет использование some, как считаешь?

2023-05-17 16:52 UTC, TorinAsakura commented on auth/scripts/index.ts
> +            throw new Error('Password must be at least 6 characters long');
полагаю вместо копипасты можно вынести это в функцию?

2023-05-19 10:20 UTC, TorinAsakura requested changes

2023-05-19 10:20 UTC, TorinAsakura commented on auth/scripts/helpers/errorHandle.ts
> +}
поправь last lines и 👍

2023-05-22 23:42 UTC, TorinAsakura requested changes
Общее замечание: Не вижу использования Promise или асинхронных операций. Это может привести к проблемам при реальном взаимодействии с базой данных или другими асинхронными операциями. Возможно, стоит пересмотреть архитектуру с учётом асинхронности.

2023-05-22 23:42 UTC, TorinAsakura commented on auth/scripts/errors.ts
> +export class ApiError extends Error {
В целом всё ок. Я бы добавил ещё описание класса и методов для ясности.

2023-05-22 23:42 UTC, TorinAsakura commented on auth/scripts/helpers/errorHandle.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
Тут тоже всё неплохо, но я бы подумал над более информативным сообщением в случае неизвестной ошибки.

2023-05-22 23:42 UTC, TorinAsakura commented on auth/scripts/helpers/userValidation.ts
> +import { ApiError } from "../errors";
Хорошо, что ты используешь валидацию, но стоит добавить ещё проверку на пустую строку. Также сообщения об ошибках стоит сделать более информативными.

2023-05-22 23:42 UTC, TorinAsakura commented on auth/scripts/index.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
В целом, всё ок, но некоторые вещи можно улучшить:

- Переменная findedUser звучит немного странно, я бы предложил foundUser
- В блоках login и register ты дублируешь код для проверки, залогинен ли уже пользователь. Это можно вынести в отдельную функцию
- При создании createdUser и activeUser, ты не используешь какую-либо форму хеширования для пароля, что является плохой практикой в целях безопасности

2023-05-22 23:42 UTC, TorinAsakura commented on auth/scripts/tests.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
Не вижу здесь никаких ассертов, это скорее похоже на набор действий. Я бы предложил использовать какую-нибудь библиотеку для тестирования, например, Jest, и добавить ассерты для проверки ожидаемого поведения.

2023-05-24 06:04 UTC, jumpeebunee commented on auth/scripts/tests.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
**Скоуп**
Установка библиотеки

**Описание**
Не получается установить какую-либо библиотеку. Везде получаю одну ошибку.

**Запуск**
```sh
yarn add --dev jest
```

**Логи**
```sh
Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

2023-05-24 10:49 UTC, jumpeebunee commented on auth/scripts/tests.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
**Скоуп**
Установка библиотеки

**Описание**
Не получается установить какую-либо библиотеку. Везде получаю одну ошибку.

**Запуск**
```sh
yarn add --dev jest
```

**Логи**
```sh
Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

2023-05-24 10:50 UTC, jumpeebunee commented on auth/scripts/tests.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
@TorinAsakura 
**Скоуп**
Установка библиотеки

**Описание**
Не получается установить какую-либо библиотеку. Везде получаю одну ошибку.

**Запуск**
```sh
yarn add --dev jest
```

**Логи**
```sh
Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

2023-05-24 21:15 UTC, TorinAsakura commented on auth/scripts/tests.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
Это не ошибка и она вообще никак не мешает работе…

2023-05-26 23:11 UTC, TorinAsakura requested changes
в целом всё круто:
- разрешить линтеру смотреть код
- пофиксить ошибки
- следи за последними строками

2023-05-26 23:11 UTC, TorinAsakura commented on auth/src/data/data.ts
> +}
последняя строка

2023-05-26 23:11 UTC, TorinAsakura commented on auth/src/helpers/errorHandle.ts
> +/* eslint no-console: 0 */  // --> off console.log errors
зачем вы отключаете линтер? я его не просто так заводил

2023-05-26 23:11 UTC, TorinAsakura commented on auth/src/service/user-service.ts
> +export default new UserService();
опять

2023-05-27 14:41 UTC, TorinAsakura approved these changes

2023-05-27 14:41 UTC, merged